# Generated by Django 5.2.5 on 2025-08-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_items',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='order_items',
            new_name='OrderItem',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_name',
            field=models.CharField(max_length=255),
        ),
    ]
